# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # app_store_connect_api_key(
    #   key_id: "B4U7H49DDK",
    #   issuer_id: "b2336353-842b-4d74-8c81-a95ff092775d",
    #   key_filepath: "/Users/thomaslau/Downloads/soulmateApp/iso/AuthKey_B4U7H49DDK.p8",
    #   duration: 1200, # optional (maximum 1200)
    #   in_house: false # optional but may be required if using match/sigh
    # )
    match(type: 'appstore')

    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    # upload_to_testflight(skip_waiting_for_build_processing: true)
    upload_to_app_store
  end

  lane :beta_ci do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    increment_build_number(build_number: number_of_commits)
    # sync_code_signing
    build_app
    changelog_from_git_commits # this will generate the changelog based on your last commits
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

 

  lane :screenshots do
    capture_screenshots # 通过快照运行应用以自动捕获屏幕截图
    upload_to_app_store # 最终截屏发送到 App Store Connect
  end
end
