default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    match(type: 'appstore')

    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end

  lane :beta_ci do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    increment_build_number(build_number: number_of_commits)
    build_app
    changelog_from_git_commits # this will generate the changelog based on your last commits
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

 

  lane :screenshots do
    capture_screenshots # 通过快照运行应用以自动捕获屏幕截图
    upload_to_app_store # 最终截屏发送到 App Store Connect
  end
end
