# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new dev release build to the App Store"
  lane :dev_store do
    init_ci
    certificates_dev
    build_number
    build_app(workspace: "Runner.xcworkspace", scheme: "dev")
    
    upload_to_app_store
  end

  desc "Push a new dev release build to the testflight"
  lane :dev_test do
    init_ci
    certificates_dev
    build_number
    build_app(workspace: "Runner.xcworkspace", scheme: "dev")
    
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Push a new prod release build to the App Store"
  lane :prod_store do
    init_ci
    certificates_prod
    build_number
    build_app(workspace: "Runner.xcworkspace", scheme: "prod")
    
    upload_to_app_store(app_identifier: "com.tob.soulmate.prod")
  end

  desc "Push a new prod release build to the testflight"
  lane :prod_test do
    init_ci
    certificates_prod
    build_number
    build_app(workspace: "Runner.xcworkspace", scheme: "prod")
    
    upload_to_testflight(skip_waiting_for_build_processing: true, app_identifier: "com.tob.soulmate.prod")
  end

  private_lane :init_ci do
    setup_ci if ENV['CI']
    login
  end

  private_lane :build_number do
    increment_build_number(build_number: latest_testflight_build_number + 1)
    # if ENV['CI']
      
    # else
    #   increment_build_number(xcodeproj: "Runner.xcodeproj")
    # end
  end

  private_lane :certificates_dev do
    match(type: "development", app_identifier: ["com.tob.soulmate.dev"])
    match(type: "appstore", app_identifier: ["com.tob.soulmate.dev"])
  end

  private_lane :certificates_prod do
    match(type: "development", app_identifier: ["com.tob.soulmate.prod"])
    match(type: "appstore", app_identifier: ["com.tob.soulmate.prod"])
  end

  desc "Get Apple API Token"
  private_lane :login do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_KEY'],
    
      duration: 1200,
      in_house: false,
      is_key_content_base64: false
    )
    UI.message "this is the api key#{api_key}"

  end
end
