name: build-ios-beta-to-testflight
on:
  push:
    branches:
      - 'beta'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Fastlane
        run: |
            gem install fastlane
      - name: Run Fastlane
        run: fastlane beta_ci
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}