name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Declare default permissions as read only.
permissions: read-all
  
jobs:
  build:
    name: Build
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: 11
          distribution: temurin
      
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter --version
          
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
    
      - name: Run build
        run: |
          flutter build ios --release --no-codesign --flavor=dev
          flutter build ios --release --no-codesign --flavor=prod
          flutter build appbundle --flavor=dev
          flutter build appbundle --flavor=prod