name: iOS dev-testFlight

on: 
  push:
    branches:
      - 'dev-testFlight'
jobs:
  build:
    name: Build Flutter Application
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter Cache
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        with:
          channel: "stable"
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          working-directory: "ios"
          bundler-cache: true

      - name: 📱 Build iOS Application
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'ios dev_test'
          subdirectory: 'ios'
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          CI: true